name: Main CI/CD Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  trigger-tests:
    name: Trigger Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Test Workflow
        uses: ./.github/workflows/test.yml
        with:
          environment: 'dev'
          test-type: 'all'
