name: Run Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'development'
      test-type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
      extra-args:
        description: 'Additional test arguments'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    # Make inputs available to all steps
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'development' }}
      TEST_TYPE: ${{ github.event.inputs.test-type || 'all' }}
      EXTRA_ARGS: ${{ github.event.inputs.extra-args || '' }}

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Generate coverage report
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
